#!/bin/bash
wget -q --content-on-error  -O -  --header "Host: community.bovada.lv" http://10.42.16.1/version |grep generator|awk -F\" '{print $4}'
wget -q --content-on-error  -O -  --header "Host: community.bovada.lv" http://10.42.16.2/version |grep generator|awk -F\" '{print $4}'
wget -q --content-on-error  -O -  --header "Host: community.bovada.lv" http://10.42.16.3/version |grep generator|awk -F\" '{print $4}'
